services:
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - myforum
      networks:
        - myforum-network

  myforum:
    build:
      context: .
      dockerfile: MyForum.Api/Dockerfile
    container_name: MyForum-api
    ports:
      - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db
      - minio
      - redis
    networks:
      - myforum-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: MyForum-postgresql
    environment:
      - POSTGRES_USER=forum
      - POSTGRES_PASSWORD=MyStrong@Passw0rd
      - POSTGRES_DB=myforumdb
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myforum-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: MyForum-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - myforum-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: myforum-promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./MyForum/Logs:/var/log/myforum:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - myforum-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: myforum-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - myforum-network
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest
    container_name: myforum-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - myforum-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: myforum-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - myforum-network
    restart: unless-stopped
    depends_on:
      - prometheus

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=MyStrong@Passw0rd
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - myforum-network

networks:
  myforum-network:
    driver: bridge
  
volumes:
  psql_data:
  grafana_data:
  minio_data:
  prometheus_data:
  redis_data: