name: Continuous Integration
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Install .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Compile
        run: dotnet build MyForum.sln

      - name: Test
        run: >
          dotnet test
          MyForum.Tests/bin/Debug/**/MyForum.Tests.dll
          --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: myForum-test-results-${{matrix.os.prettyname}}-${{matrix.threadingMode}}
          path: ${{github.workspace}}/TestResults/TestResults-${{matrix.os.prettyname}}-${{matrix.threadingMode}}.trx
